SOCIAL_AUTH_TWITTER_KEY = 'lSiqQSgMB4dJgB3odOBuUzG1Q'
SOCIAL_AUTH_TWITTER_SECRET = 'CUMWlaS1J4lOfOHfyuKyk67DDVfeqrdce0JHXlw0NXHFPVWQ8z'
SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/'
SOCIAL_AUTH_LOGIN_URL = '/login/'
